Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 40
